filename: github-metrics.svg
template: classic
plugins_errors_fatal: false
plugins:
  languages:
    enabled: true
  achievements:
    enabled: true
  calendar:
    enabled: true
  activity:
    enabled: true
  streaks:
    enabled: true
