name: Achievements

on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  github-achievements:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Achievements
        uses: lowlighter/metrics@latest

        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: millareskenneth

          template: classic
          base: ""
          filename: github-achievements.svg
          output_action: commit

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X