name: Isocalendar Full Year

on:
  schedule:
    - cron: "0 8 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  github-isocalendar-full:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Full-year Calendar
        uses: lowlighter/metrics@latest

        with:
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          base: ""
          filename: github-isocalendar-full.svg
          output_action: commit

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
