name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@v3.34
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: millareskenneth
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
          plugin_traffic: yes
